# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 config.vm.box = "centos/7"

 config.vm.network "forwarded_port", guest: 80, host: 4000
 config.vm.network "private_network", ip: "192.168.167.166"

 config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
 end

 config.vm.provision :itamae do |config|
   config.shell = "/bin/sh"
   config.sudo = true
   config.recipes = ['./recipe.rb']
 end
end
